Design: 채널바 height 수정
TheUpperPart/leaguehub-frontend pull request #135
Opened 2023-09-10 09:45 UTC by navyjeongs

## 🤠 개요

- closes: #133 
- 채널바를 100vh 이상 확대되도록 변경했어요.

## 💫 설명
- 현재 채널바의 height가 100vh로 되어있는데 채널 생성등의 경우에는 contents가 100vh가 넘어가 채널바가 짤리는 상황이 발생했어요.
- 그래서 채널바의 min-height를 100vh로 하고 height는 100%로 하여 100vh이상 높이가 커지도록 변경했어요.

## 📷 스크린샷 (Optional)
- 전
<img width="766" alt="Screenshot 2023-09-10 at 6 39 50 PM" src="https://github.com/TheUpperPart/leaguehub-frontend/assets/100738049/4f1828dd-e93b-4ef4-889b-f82a4dcc5f41">

- 후
<img width="823" alt="Screenshot 2023-09-10 at 6 41 16 PM" src="https://github.com/TheUpperPart/leaguehub-frontend/assets/100738049/8ca1abd9-8df5-4aa1-bae4-4c258a76c280">

2023-09-11 06:11 UTC, pp449 requested changes
스크롤되는게 불편할수도 있을거 같은데 전체 페이지는 스크롤되지 않도록 하고 내부 콘텐츠에서 스크롤되게 하면 어떨까요?

2023-09-11 10:19 UTC, navyjeongs commented
> 스크롤되는게 불편할수도 있을거 같은데 전체 페이지는 스크롤되지 않도록 하고 내부 콘텐츠에서 스크롤되게 하면 어떨까요?

그게 훨씬 좋을 것 같네요. 해당 부분 적용할게요!

2023-09-14 14:41 UTC, navyjeongs commented
> 스크롤되는게 불편할수도 있을거 같은데 전체 페이지는 스크롤되지 않도록 하고 내부 콘텐츠에서 스크롤되게 하면 어떨까요?

![녹화_2023_09_14_23_37_12_443](https://github.com/TheUpperPart/leaguehub-frontend/assets/100738049/bb1d28ea-f062-4cbd-86da-d512e6d8dd43)

100vh를 넘어가면 스크롤이 생기게 변경했습니다.
스크롤 디자인을 일단 임의로 했어요!

2023-09-15 01:19 UTC, pp449 approved these changes
✅ 훨씬 좋은거 같아요!

2023-09-16 07:16 UTC, merged