Feat/#13 ChannelCircle 컴포넌트 구현
TheUpperPart/leaguehub-frontend pull request #31
Opened 2023-06-12 05:34 UTC by navyjeongs

## 🤠 개요
- closes: #13 
- ChannelCircle 컴포넌트를 테스트 하고 구현했어요.

## 💫 설명
- 테스트에서는 컴포넌트가 있는지, 배경 이미지가 있다면 잘 표시되는지를 확인했어요!
- 아래 스크린샷을 보면 왼쪽은 배경 이미지가 없을 때고 오른쪽은 배경 이미지가 있을 때예요. 배경 이미지가 없을 때는 괜찮은데 만약 배경 이미지가 있다면 글자 색을 배경 이미지와 다른 색상으로 설정해야 텍스트가 표시돼요!
- 따라서 배경 이미지가 있다면 배경 이미지 색상에 따라 다른 글자 색을 사용할 건지 텍스트를 안 보이게 할 건지는 추후에 논의해야 할 것 같아요!

## 📷 스크린샷 (Optional)
<img width="250" alt="1111" src="https://github.com/TheUpperPart/leaguehub-frontend/assets/100738049/ead8ebd6-3ab1-41bf-acac-18843ca75d4e">

2023-06-12 06:48 UTC, pp449 requested changes

2023-06-12 06:48 UTC, pp449 commented on src/components/Sidebar/ChannelCircle/ChannelCircle.tsx
> +}
pages 디렉토리에서 ChannelCircle 컴포넌트를 이용할 때 해당 interface 가 필요할거 같은데 이름을 ChannelCircleProps 로 해서 @types 로 빼는건 어떨까요??

2023-06-12 10:51 UTC, navyjeongs commented on src/components/Sidebar/ChannelCircle/ChannelCircle.tsx
> +}
> pages 디렉토리에서 ChannelCircle 컴포넌트를 이용할 때 해당 interface 가 필요할거 같은데 이름을 ChannelCircleProps 로 해서 @types 로 빼는건 어떨까요??

좋은 것 같아요!! type 분리하겠습니다!

2023-06-13 07:36 UTC, pp449 approved these changes
LGTM👍

2023-06-14 01:49 UTC, merged