Feat/#41: 사이드바 (게시판) 구현
TheUpperPart/leaguehub-frontend pull request #44
Opened 2023-06-22 01:49 UTC by pp449

## 🤠 개요

- closes: #41 
- 게시판을 구현했는데 커밋이 많아요..

## 💫 설명
## 만들어진 기능
- 채널 선택 시 선택된 채널을 관리하는 기능
- 게시판 선택 시 선택된 게시판을 관리하는 기능

## 안만들어진 기능
- 공지 추가하기/리그 참여하기 의 경우 모달창을 이용할거 같아서 클릭 이벤트가 아직 아무것도 없어요
- 게시판 리스트 (공지사항, 참여자규칙)를 클릭했을 때 id 값을 이용해 선택 상태를 관리했고 페이지(URL) 변경은 구현 안했어요
- 해당 리그를 참여하는 사람(팀)을 클릭했을 때 이벤트도 아직 없어요

## 아쉬운점
- 작업의 볼륨이 커서 해당 이슈에 대해 이슈를 또 나눠서 작업한 후 squash merge 하는게 더 괜찮을거 같다는 생각이 들었어요

## 📷 스크린샷 (Optional)
참고사항 : 3번째 채널과 4번째 채널은 같은 데이터를 이용하고 있어요
![image](https://github.com/TheUpperPart/leaguehub-frontend/assets/71641127/2140f278-7b89-4039-981b-7e50ba2968ef)

2023-06-23 10:34 UTC, navyjeongs commented on __mocks__/handlers/boardHandlers.ts
> +    let boardInfo: BoardInfo | undefined;
undefined는 channelid에 해당하는 채널이 없을 때를 나타내는 건가요?

2023-06-23 10:37 UTC, navyjeongs commented on __mocks__/handlers/boardHandlers.ts
> +    const { channelid } = req.params;
혹시 카멜케이스를 사용하는 것은 어떨까요?
channelid -> channelId

2023-06-23 10:41 UTC, navyjeongs requested changes

2023-06-23 10:41 UTC, navyjeongs commented on src/components/Sidebar/BoardBar/BoardBar.tsx
> +        </div>
해당 div는 삭제해도 괜찮을것 같아요!! 없어도 차이가 없을 것 같아요.

2023-06-23 10:49 UTC, navyjeongs commented on src/components/Sidebar/BoardBar/BoardBody.tsx
>    ${({ isSelected }) => isSelected && `background-color: #39587E`}
사용자가 hover 했을 때 hover 했음을 알 수 있게  hover에 background-color를 추가해도 좋을 것 같아요! 
isSelected의 배경색보다 조금 연하게!!

2023-06-24 03:09 UTC, pp449 commented on __mocks__/handlers/boardHandlers.ts
> +    let boardInfo: BoardInfo | undefined;
undefined는 처음 boardInfo 선언했을때 값이 넣어주지 않아서 undefined 를 추가했는데없어도 되는군요 
undefined 는 지우겠습니다

2023-06-24 03:11 UTC, pp449 commented on __mocks__/handlers/boardHandlers.ts
> +    const { channelid } = req.params;
카멜케이스를 이용하니까 l과 대문자 i 가 구분이 안될거 같아서 id 로 했는데 channelId 로 하는게 좋을까요?
깃북에는 channel-id 였는데 const { channel-id } = req.params; 로 값을 못받아 오더라고요

2023-06-24 03:14 UTC, pp449 commented on src/components/Sidebar/BoardBar/BoardBar.tsx
> +        </div>
그렇군요 div 는 없애도록 할게요

2023-06-24 03:20 UTC, navyjeongs commented on __mocks__/handlers/boardHandlers.ts
> +    const { channelid } = req.params;
저는  api에서 path-variable을 사용할 때 카멜케이스를 써야하는 것으로 알고 있었는데 찾아보니깐 딱히 정해진 것은 없어서 지금 처럼해도 될 것 같아요!!

https://restfulapi.net/resource-naming/

2023-06-24 03:24 UTC, pp449 commented
피드백 내용 모두 반영해서 수정했어요!

2023-06-25 04:00 UTC, navyjeongs approved these changes

2023-06-25 04:00 UTC, navyjeongs commented
Good~

2023-06-25 05:39 UTC, merged