Feat/#42 헤더 컴포넌트 개발
TheUpperPart/leaguehub-frontend pull request #47
Opened 2023-06-26 09:29 UTC by navyjeongs

## 🤠 개요
- closes: #42 
- 헤더 컴포넌트에서 로그인 여부를 판별해서 로그인 여부에 따라 다른 헤더를 보여주도록 구현했어요.

## 💫 설명
1. LoginContext 삭제 후 ProfileContext 생성
- 기존에는 Login을 하면 이름과 프로필 이미지 주소를 받아오기로 했는데 프로필을 가져오는 api를 따로 만들기로 결정했기 때문에 LoginContext를 삭제하고 ProfileContext를 생성했어요.

2. profile 가져오는 useQuery 작성
- layout.tsx에서 accessToken이 있다면 로그인 되었다고 판별한 후 프로필을 가져오는 api를 호출해요.
- api를 호출하고 정상적으로 데이터를 받아왔다면 useEffect에서 이름과 프로필 주소를  ProfileContext에 저장해요.

3. Header에서 판별
- 헤더 컴포넌트에서 ProfileContext에 값이 있다면 로그인되었다고 판별하고 프로필 이미지와 이름을 보여주고 아니면 로그인 버튼을 보여줘요.

4. 지금 PR에는 헤더 좌측에 현재 접속하고 있는 게시판 이름을 보여주는 것을 구현하지 않았어요.
- 이 부분은 사용자가 다른 대회를 클릭할 때마다 혹은 다른 게시판을 클릭 할 때마다 최종적으로 접속한 대회와 게시판 이름을 localStorage에 저장하고 해당 값을 Context에 불러와서 사용하면 될 것 같은데 얘기해 보고 결정해야 할 것 같아요.
- localStorage에 저장하려는 이유는 사용자가 저희 서비스를 다시 접속했을 때 최종적으로 접속했던 대회와 게시판을 보여주는 것이 사용자에게 편리할 것 같아서예요!

## 📷 스크린샷 (Optional)
- 비로그인 상태
<img width="797" alt="비로그인" src="https://github.com/TheUpperPart/leaguehub-frontend/assets/100738049/e88ba1a6-58aa-4d36-80f0-12cd2c742ee2">

- 로그인 상태
<img width="797" alt="로그인" src="https://github.com/TheUpperPart/leaguehub-frontend/assets/100738049/428b7e49-985b-4fac-8e9c-165e0ba807be">

2023-06-29 12:21 UTC, pp449 requested changes
리팩토링 관련해서 질문드려요!

2023-06-29 12:21 UTC, pp449 commented on src/apis/fetchProfile.ts
fetchProfile 함수가 추가적으로 사용될 곳이 있을까요?
따로 정의한 이유가 궁금합니다!

2023-06-29 12:21 UTC, pp449 commented on src/components/Header/Header.tsx
>    return (
``` tsx
<ProfileImg src={context.profile.profileUrl} width={24} height={24} alt='profile' />
<Text>{context.profile.nickname}</Text>
```

해당 라인만 다르고 나머지는 동일하니 return 을 2번 사용하는 것 보단 삼항연산자를 이용하는건 어떨까요?
``` tsx
return (
      <Headers>
        <Container>
          <LoginBtn onClick={handleLink}>
            {context?.profile ? <ProfileImg src={context.profile.profileUrl} width={24} height={24} alt='profile' />
            <Text>{context.profile.nickname}</Text> : <Icon kind='my' color='white' size={24} />
          <Text>로그인</Text>
        </LoginBtn>
      </Container>
    </Headers>
  );
  ```

2023-06-29 12:21 UTC, pp449 commented on src/components/layout.tsx
> +
전역 상태 데이터를 관리하는 부분을 layout 컴포넌트보다 더욱 연관성있는 ProfileProvider.tsx 에서 설정하도록 하는게 어떨까요?
layout에 너무 많은 코드가 있어서 나중에 관리하기 힘들 수 있을거 같아요!

2023-07-01 02:48 UTC, navyjeongs commented on src/apis/fetchProfile.ts
저는 SOC를 지키기 위해 api 로직을 컴포넌트에서 분리하여 주로 api 폴더에서 관리하는 편인데 컴포넌트에서 작성해도 괜찮을 것 같은데 컴포넌트에서 요청할까요??

2023-07-01 02:48 UTC, navyjeongs commented on src/components/Header/Header.tsx
>    return (
로그인 버튼이 추후에 마이페이지 버튼으로 변경될 예정이기 때문에 위와 비슷하게 삼항 연산자를 사용하여 우선적으로 처리하겠습니다!!

2023-07-01 02:49 UTC, navyjeongs commented on src/components/layout.tsx
> +
좋은 것 같아요!! ProfileProvider에서 설정할게요!

2023-07-02 06:38 UTC, pp449 commented on src/apis/fetchProfile.ts
넵 재사용이 되지 않는다면 모듈화를 하는게 오히려 가독성이 떨어질 수 있다는 생각이 들어요
그래서 메인 로직에 같이 넣어두는게 좋을거 같아요

2023-07-02 06:43 UTC, pp449 commented on src/components/Header/Header.tsx
>    return (
아직 추가로 해야할 작업이 남았었군요 알겠습니다!

2023-07-03 06:16 UTC, pp449 approved these changes
헤더 구현 확인했습니다!

2023-07-03 06:42 UTC, merged